### ISSUE TITLE
Decide what the initial set of pruning functions will be.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/shears#1]
**Overview of this Issue**

For the initial release of shears, a set of pruning functions to implement should be decided upon.

**Tasks to Close Issue**

- [x] Decide the pruning functions to implement for the first release. Post them in a reply to this issue.
- [x] Design each pruning function's signature. Post them in a reply to this issue.
- [x] Create issues for the implementation of each function.

**Comment by mikesiers** [comment]
*Initial Pruning Functions*

- pessimistic_prune(node, confidence) : Returns `True` if `node` should be pruned. `False` otherwise.
- cost_based_prune(node, confidence, cost_matrix) : Returns `True` if `node` should be pruned. `False` otherwise.

*Auxiliary Functions*

- estimated_errors(num_errors, num_records, confidence) : Returns a float for the estimated number of errors.
- estimated_cost_errors(num_errors, num_records, confidence, cost_matrix) : Returns a float for the estimated number of errors.

**Comment by mikesiers** [comment]
The work required to close this issue has been completed.
