### ISSUE TITLE
Implement estimated_errors function.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/shears#2]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

The estimated number of errors for a node is calculated as the upper limit of the confidence belt. In the book [C4.5 programs for machine learning](https://books.google.com.au/books?isbn=1558602380), Quinlan used the Clopper-Pearson method to calculate this value. There is a [nice and quick snippet of code](https://gist.github.com/DavidWalz/8538435) in python which implements this method. It should be appropriated and credited for shears.

**Tasks to Close Issue**

- [x] Write the function signature and a description of its parameters and return type. Post them in a reply to this issue.
- [x] Design unit tests for this function. Post them in a reply to this issue.
- [x] Implement the unit tests.
- [x] Implement `estimated_errors`.
- [x] Ensure that the unit tests pass.
- [x] Generate documentation.

**Comment by mikesiers** [comment]
*Function signature*

estimated_errors(num_errors, num_records, confidence) : Returns a float for the estimated number of errors.

*Parameter descriptions*

- num_errors : An integer number describing how many errors are made by this node.
- num_records : An integer number describing how many records are covered by this node (the number of training cases).
- confidence : The confidence level to use for this pruning. For more information on this parameter, see the chapter on pruning in [Quinlan's C4.5 book](https://books.google.com.au/books?isbn=1558602380). Optional, default = 25.

*Raises*

- ValueError if num_errors > num_records.
- ValueError if num_errors < 0.
- ValueError if num_records < 0.
- ValueError if confidence is not in [0, 50]

**Comment by mikesiers** [comment]
*Unit Tests*

- Check that the correct output is produced for the three examples on page 41 of [C4.5 programs for machine learning](https://books.google.com.au/books?isbn=1558602380).
- Check that an error is raised if num_errors > num_records.
- Check that an error is raised if num_errors < 0.
- Check that an error is raised if num_records < 0.
- Check that an error is raised if confidence is not in [0, 50]
