### ISSUE TITLE
Implement estimated_cost_errors function.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/shears#3]
**Prerequisite Issues**

- [x] #1 
- [ ] #2 

**Overview of this Issue**

This function is very similar to the `estimate_errors` function (see Issue #2). The only difference is how to count the errors. In `estimate_errors`, errors are considered to be records which don't belong to the class which has the most records in that node. `estimate_cost_errors` differs since errors are considered to be records which don't belong to the class which has the lowest cost (i.e, C\_P, C\_N see [here](https://github.com/mikesiers/DataCost/blob/master/README.md) for more details).

**Tasks to Close Issue**

- [ ] Write the function signature and a description of its parameters and return type. Post them in a reply to this issue.
- [ ] Design unit tests for this function. Post them in a reply to this issue.
- [ ] Implement the unit tests.
- [ ] Implement `estimated_cost_errors`.
- [ ] Ensure that the unit tests pass.
- [ ] Generate documentation.

**Comment by mikesiers** [comment]
This function will not be needed since it will have the exact some implementation as `expected_errors`. Therefore, it is removed from shears.
