### ISSUE TITLE
Implement pessimistic_prune function.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/shears#4]
**Prerequisite Issues**

- [x] #1 
- [x] #2 

**Overview of this Issue**

Given a decision tree node ([wattle.Node](https://github.com/mikesiers/wattle)) and a confidence level, this function determines whether or not the node should be pruned. For this reason, the return type is Boolean. The core of this function is implemented in `estimated_errors` (see Issue #2).

This function can be expressed as an algorithm as follows:
---
Function pessimistic_prune(node, confidence):
1. Check that all of node's children are leaves. If any are, throw an input error.
2. Calculate the estimated errors for each child using `estimated_errors`.
3. Calculate the sum of all the children's estimated errors.
4. Calculate the support counts of node if the pruning were to happen.
5. Based on the support counts calculated in Step 4, calculate the estimated errors for node.
6. If the number of estimated errors for node is ≤ the sum of estimated errors for the children, prune the node.
---

**Tasks to Close Issue**

- [x] Write the function signature and a description of its parameters and return type. Post them in a reply to this issue.
- [x] Design unit tests for this function. Post them in a reply to this issue.
- [ ] Implement the unit tests.
- [x] Implement `pessimistic_prune`.
- [ ] Ensure that the unit tests pass.
- [ ] Generate documentation.

**Comment by mikesiers** [comment]
*Function signature*

pessimistic_prune(node, confidence) : Returns `True` if `node` should be pruned. `False` otherwise.

*Parameter descriptions*

- node : a [wattle.Node](https://github.com/mikesiers/wattle) which has only leaves as children. This is the node that will be considered for pruning.
- confidence : The confidence level to use for this pruning. For more information on this parameter, see the chapter on pruning in [Quinlan's C4.5 book](https://books.google.com.au/books?isbn=1558602380). Optional, default = 25.

*Raises*

- ValueError if `node` has a child which isn't a leaf.

**Comment by mikesiers** [comment]
*Unit Tests*

- Check that an error is raised if `node` has a child which isn't a leaf.
- Check that a node is pruned when expected.
- Check that a node is not pruned when expected to not prune.
