### ISSUE TITLE
Implement cost_based_prune function.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/shears#5]
**Prerequisite Issues**

- [x] #1 
- [ ] #2 

**Overview of this Issue**

Given a decision tree node ([wattle.Node](https://github.com/mikesiers/wattle)) and a confidence level, this function determines whether or not the node should be pruned. For this reason, the return type is Boolean. The core of this function is implemented in `estimated_errors` (see Issue #2).

The main difference between this function and `pessimistic_prune` (see Issue #4) is that the number of errors is calculated differently. The only difference is how to count the errors. In `pessimistic_prune`, errors are considered to be records which don't belong to the class which has the most records in that node. `cost_based_prune ` differs since errors are considered to be records which don't belong to the class which has the lowest cost (i.e, C\_P, C\_N see [here](https://github.com/mikesiers/DataCost/blob/master/README.md) for more details).

This function can be expressed as an algorithm as follows:
---
Function cost_based_prune(node, confidence, cost_matrix):
1. Check that all of node's children are leaves. If any are, throw an input error.
2. Calculate the estimated errors for each child using `estimated_errors`.
3. Calculate the sum of all the children's estimated cost errors.
4. Calculate the support counts of node if the pruning were to happen.
5. Based on the support counts calculated in Step 4, calculate the estimated errors for node.
6. If the number of estimated errors for node is ≤ the sum of estimated errors for the children, prune the node.
---

**Tasks to Close Issue**

- [x] Write the function signature and a description of its parameters and return type. Post them in a reply to this issue.
- [x] Design unit tests for this function. Post them in a reply to this issue.
- [ ] Implement the unit tests.
- [ ] Implement `cost_based_prune`.
- [ ] Ensure that the unit tests pass.
- [ ] Generate documentation.

**Comment by mikesiers** [comment]
*Function signature*

cost_based_prune(node, confidence, cost_matrix) : Returns `True` if `node` should be pruned. `False` otherwise.

*Parameter descriptions*

- node : a [wattle.Node](https://github.com/mikesiers/wattle) which has only leaves as children. This is the node that will be considered for pruning.
- confidence : The confidence level to use for this pruning. For more information on this parameter, see the chapter on pruning in [Quinlan's C4.5 book](https://books.google.com.au/books?isbn=1558602380). Optional, default = 0.25.
- cost_matrix : A dictionary of costs which represent the cost matrix. For example: {'TP' : 1, 'TN' : 0, 'FP' : 1, 'FN' : 5}. It is used to determine the values of C\_P and C\_N (see [here](https://github.com/mikesiers/DataCost/blob/master/README.md) for details on these values). These values are used to determine the label of this node. From that label, the number of errors can be calculated.

*Raises*

- ValueError if `cost_matrix` is missing a required cost.
- ValueError if `node` has a child which isn't a leaf.

**Comment by mikesiers** [comment]
*Unit Tests*

- Check that an error is raised if `cost_matrix` is missing a required cost.
- Check that an error is raised if `node` has a child which isn't a leaf.
- Check that a node is pruned when expected.
- Check that a node is not pruned when expected to not prune.
