### ISSUE TITLE
Implement total_cost_prune function. (Defined in this issue).

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/shears#7]
**Prerequisite Issues**

- [x] #1  

**Overview of this Issue**

Given a decision tree node ([wattle.Node](https://github.com/mikesiers/wattle)) and a confidence level, this function determines whether or not the node should be pruned. For this reason, the return type is Boolean. The core of this function is implemented in `DataCost.total_cost` (see [DataCost](https://github.com/mikesiers/DataCost)).

This function can be expressed as an algorithm as follows:
---
Function total_cost_prune(node, confidence):
1. Check that all of node's children are leaves. If any are, throw an input error.
2. Calculate the estimated errors for each child using `DataCost.total_cost`.
3. Calculate the sum of all the children's total cost.
4. Calculate the support counts of node if the pruning were to happen.
5. Based on the support counts calculated in Step 4, calculate the total cost for node.
6. If the total cost for node is ≤ the sum of total costs for the children, prune the node.
---

**Tasks to Close Issue**

- [x] Write the function signature and a description of its parameters and return type. Post them in a reply to this issue.
- [x] Design unit tests for this function. Post them in a reply to this issue.
- [ ] Implement the unit tests.
- [ ] Implement `pessimistic_prune`.
- [ ] Ensure that the unit tests pass.
- [ ] Generate documentation.

**Comment by mikesiers** [comment]
*Function signature*

total_cost_prune(node, cost_matrix) : Returns `True` if `node` should be pruned. `False` otherwise.

*Parameter descriptions*

- node : a [wattle.Node](https://github.com/mikesiers/wattle) which has only leaves as children. This is the node that will be considered for pruning.
- cost_matrix : A dictionary of costs which represent the cost matrix. For example: {'TP' : 1, 'TN' : 0, 'FP' : 1, 'FN' : 5}. It is used to determine the values of C\_P and C\_N (see [here](https://github.com/mikesiers/DataCost/blob/master/README.md) for details on these values). These values are used to calculate the total cost of the node.

*Raises*

- ValueError if `cost_matrix` is missing a required cost.
- ValueError if `node` has a child which isn't a leaf.

**Comment by mikesiers** [comment]
*Unit Tests*

- Check that an error is raised if `node` has a child which isn't a leaf.
- Check that a node is pruned when expected.
- Check that a node is not pruned when expected to not prune.
